In [2]:
import pandas as pd 
from io import StringIO
data ='{"emplyee_name":"Shristi","email":"shristijha39@gmail.com","job_profile":[{"title1":"Team lead","title2":"Sr.Developer"}]}'
df = pd.read_json(StringIO(data))

In [3]:
df

,emplyee_name,email,job_profile
0,Shristi,shristijha39@gmail.com,"{'title1': 'Team lead', 'title2': 'Sr.Developer'}"

In [5]:
df.to_json()

'{"emplyee_name":{"0":"Shristi"},"email":{"0":"shristijha39@gmail.com"},"job_profile":{"0":{"title1":"Team lead","title2":"Sr.Developer"}}}'

In [6]:
df.to_json(orient='index')

'{"0":{"emplyee_name":"Shristi","email":"shristijha39@gmail.com","job_profile":{"title1":"Team lead","title2":"Sr.Developer"}}}'

In [7]:
df.to_json(orient='records')

'[{"emplyee_name":"Shristi","email":"shristijha39@gmail.com","job_profile":{"title1":"Team lead","title2":"Sr.Developer"}}]'

In [10]:
pd.read_csv("WineQT.csv")

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,0
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5,1
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5,2
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6,3
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1138,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6,1592
1139,6.8,0.620,0.08,1.9,0.068,28.0,38.0,0.99651,3.42,0.82,9.5,6,1593
1140,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5,1594
1141,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6,1595
1142,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5,1597

In [11]:
df.to_csv("wine.csv")

In [12]:
!pip install lxml

Requirement already satisfied: lxml in c:\users\kiit0001\anaconda3\lib\site-packages (5.3.0)

In [13]:
url="https://gist.github.com/lillylangtree/b55828fa05ed3470d352"

df=pd.read_html(url)

In [14]:
df

[     0                                                  1
 0  NaN                                    <!DOCTYPE html>
 1  NaN                                                NaN
 2  NaN                                             <html>
 3  NaN                                             <head>
 4  NaN  <meta http-equiv="Content-Type" content="text/...
 5  NaN                         <title>Spoon-Knife</title>
 6  NaN  <LINK href="styles.css" rel="stylesheet" type=...
 7  NaN                                            </head>
 8  NaN                                                NaN
 9  NaN                                             <body>
 10 NaN                                                NaN
 11 NaN       <img src="forkit.gif" id="octocat" alt="" />
 12 NaN                                                NaN
 13 NaN        <!-- Feel free to change this text here -->
 14 NaN                                                <p>
 15 NaN                       Fork me? Fork you, @octocat!
 16 NaN                                               </p>
 17 NaN                                                <p>
 18 NaN                                 Sean made a change
 19 NaN                                               </p>
 20 NaN                                                NaN
 21 NaN                                            </body>
 22 NaN                                            </html>]

In [15]:
df[0]

     0                                                  1
0  NaN                                    <!DOCTYPE html>
1  NaN                                                NaN
2  NaN                                             <html>
3  NaN                                             <head>
4  NaN  <meta http-equiv="Content-Type" content="text/...
5  NaN                         <title>Spoon-Knife</title>
6  NaN  <LINK href="styles.css" rel="stylesheet" type=...
7  NaN                                            </head>
8  NaN                                                NaN
9  NaN                                             <body>
10 NaN                                                NaN
11 NaN       <img src="forkit.gif" id="octocat" alt="" />
12 NaN                                                NaN
13 NaN        <!-- Feel free to change this text here -->
14 NaN                                                <p>
15 NaN                       Fork me? Fork you, @octocat!
16 NaN                                               </p>
17 NaN                                                <p>
18 NaN                                 Sean made a change
19 NaN                                               </p>
20 NaN                                                NaN
21 NaN                                            </body>
22 NaN                                            </html>

In [ ]:
df_excel=pd.read_excel('data.xlsx')

In [ ]:
df_excel.topickle('df_excel')

In [ ]:
pd.read_pickle('df_excel')