### Data Encoding
1.Nominal/OHE Encoding
2.LAbel and Ordinal Encoding
3.TArget Guided Ordinal Encoding

### Nominal/OHE Encoding
One hot encoding ,also known as nominal encoding is a technique used to categorical data as numerical data,which is more suiable for ml algorithms.In this technique,each category is represented as a binary vector where each bit corresponds to a unique category.For example,if we have a categorical variable "color" with the possible values(red,green,blue),we can represent it in one hot encoding as follows:

1.Red:[1,0,0]

2.Green:[0,1,0]

3.Blue:[0,0,1]

In [2]:
import pandas as pd
from sklearn.preprocessing  import OneHotEncoder

In [3]:
### Create a simple Dataframe
df = pd.DataFrame({
  'color':['red','blue','green','green','red','blue']
})

In [4]:
df.head()

   color
0    red
1   blue
2  green
3  green
4    red

In [6]:
## Create an instance of OneHotEncoder
encoder= OneHotEncoder()

In [11]:
## perform fit and transform
encoded=encoder.fit_transform(df[['color']]).toarray()

In [12]:
import pandas as pd
encoder_df=pd.DataFrame(encoded,columns=encoder.get_feature_names_out())

In [14]:
encoder_df

   color_blue  color_green  color_red
0         0.0          0.0        1.0
1         1.0          0.0        0.0
2         0.0          1.0        0.0
3         0.0          1.0        0.0
4         0.0          0.0        1.0
5         1.0          0.0        0.0

In [15]:
encoder.transform([['blue']]).toarray()

c:\Users\KIIT0001\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

array([[1., 0., 0.]])

In [16]:
pd.concat([df,encoder_df],axis=1)

   color  color_blue  color_green  color_red
0    red         0.0          0.0        1.0
1   blue         1.0          0.0        0.0
2  green         0.0          1.0        0.0
3  green         0.0          1.0        0.0
4    red         0.0          0.0        1.0
5   blue         1.0          0.0        0.0